# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'GPA Calculator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'ProgressHUD'
  # Pods for GPA Calculator

  target 'GPA CalculatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GPA CalculatorUITests' do
    # Pods for testing
  end

end
